export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

export const LOAD_STATUS_SUCCESS = 'LOAD_STATUS_SUCCESS';
export const LOAD_STATUS_FAILURE = 'LOAD_STATUS_FAILURE';

export const SET_NODE_STATUS = 'SET_NODE_STATUS';

export const START_NODE_SUCCESS = 'START_NODE_SUCCESS';
export const START_NODE_FAILURE = 'START_NODE_FAILURE';

export const STOP_NODE_SUCCESS = 'STOP_NODE_SUCCESS';
export const STOP_NODE_FAILURE = 'STOP_NODE_FAILURE';

export const RESTART_NODE_SUCCESS = 'RESTART_NODE_SUCCESS';
export const RESTART_NODE_FAILURE = 'RESTART_NODE_FAILURE';

export const UPDATE_NODE_SUCCESS = 'UPDATE_NODE_SUCCESS';
export const UPDATE_NODE_FAILURE = 'UPDATE_NODE_FAILURE';
